

container-name-run : mern-example-run
container-name-tools : mern-example-tools

host-path-run : ""
host-path-tools : "."

container-path-run : ""
container-path-tools : "/usr/app"

container-port-map : "3000:3000,3100:3100"
container-port-map-debug : "5858:5858"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

image-name-run : "mern-example-image-run"
image-name-tools : "mern-example-image-tools"

build-cmd-run : "/bin/echo hi"
test-cmd : "npm test"
build-cmd-debug : "npm run start-dev"

run-cmd : "npm run start"
debug-cmd : "npm run start-dev"